### ISSUE TITLE
Stabilize rulesets changes

### ISSUE THREAD

**Issue by aufi** [konveyor/ci#27]
There is a https://github.com/konveyor/rulesets repository that contains analysis rules converted from windup (by a windup-shim). These rules define issues created by the analysis process.

The latest update of ruleset https://github.com/konveyor/rulesets/pull/35 introduced few changes:
- Perl-compatible regex for rules local-storage-00003 were added (e.g. `(([:=(,\{])([ ])*(["'])?([a-zA-Z]):)(?<![\<\\\/\d\w])([\\\/]\w+)+(\.\w+)?`) in 07-local-storage.windup.yaml (and 160-...) https://github.com/konveyor/rulesets/pull/35/files#diff-419f2137a5a26ca077059dbf64df44b44dce0a244d08f99ae8bcd4a9b99cb57eR118 and https://github.com/konveyor/rulesets/pull/35/files#diff-6dda044f417298b73d164cfd93a6a93ff95dfe0110ef214f86c6d679273c1050R118) and failed to be parsed by golang tools (this was **failing the analysis**)
- ruleset reporting localstorage and related issues was renamed from `openshift` to `cloud-readiness`
- issue messages were slightly changes (just spaces or new lines, but different string for test)

There were few quick fixes addressing issues above created on Friday Dec 8th. For a long-term stability, following steps should be done (feel free to modify or add new ones)

### Proposal

- [x] a gate CI action on PRs in https://github.com/konveyor/rulesets repository should be created
- [ ] ruleset generate process in windup-shim might be update (if needed and makes sense ?)
- [ ] changes in API E2E analysis test needs to be confirmed to be correct&expected by users https://github.com/konveyor/go-konveyor-tests/pull/72/files
  - [ ] rename `openshift` to `cloud-readiness` https://github.com/konveyor/go-konveyor-tests/pull/72/files#diff-8de8d68fcf79068091ebb8dd937441c177b445478316b12ac18a0dbaa29f9177R54
  - [ ] incident messages starting with newline and space https://github.com/konveyor/go-konveyor-tests/pull/72/files#diff-8de8d68fcf79068091ebb8dd937441c177b445478316b12ac18a0dbaa29f9177R60
  - [ ] decide if we want test `potential` issues reported by technology-usage ruleset, that were not reported before https://github.com/konveyor/go-konveyor-tests/pull/72/files#diff-ccf64025a7868dbe8a17d16aa2779b5c6c1656a13377c2d85763d26136c64342R141

**Comment by jmle** [comment]
I think we need to bare in mind a few things regarding the converted rules:

1. We might still need to change the format of the rules in the future.
2. There will probably be new windup rules that we need to convert.
3. The shim is stuck at the moment at windup-rulesets version `6.2.3`, but we manually added/altered some rules after that.

Given this, I think we need to:
1. Use windup-rulesets as the single source of truth. No manual modifications should be done to our rulesets.
2. Use the shim to make all the changes needed to the rules so that we don't need to modify them afterwards.
3. Translate all windup rules, also the ones from `6.2.3` on. I think that version was set to achieve the goal of 80% coverage in the past, but we need to move forward and bring everything. ATM we have almost everything, but some of the stuff was added manually. This breaks conversion.
4. Maybe have a document with information regarding decisions taken and conversion strategies. For instance, I might have accidentally added `potential` rules, maybe it was decided in the past that we didn't want to show them?

What do you think?

**Comment by shawn-hurley** [comment]
> There will probably be new windup rules that we need to convert.

I disagree, all new rules that we are supporting once we release must be in the new format. Supporting two formats is already too much of a burden. 

> The shim is stuck at the moment at windup-rulesets version 6.2.3, but we manually added/altered some rules after that.

This is by design; we have to move to a world where we are not talking about windup rules, but we are talking about our rulesets. The shim and conversation were always meant to be a starting point and to move forward with our rulesets. 

Is there some other reason?

**Comment by jmle** [comment]
> I disagree, all new rules that we are supporting once we release must be in the new format. Supporting two formats is already too much of a burden.

I'm not proposing to support two different formats. There may be new rules coming from windup in the future that we will want to move over to konveyor. Of course they will be in the new format once they are translated.

> This is by design; we have to move to a world where we are not talking about windup rules, but we are talking about our rulesets. The shim and conversation were always meant to be a starting point and to move forward with our rulesets.

I agree with this, but again, I think we will probably have to move new rules over to konveyor. There will be a transitional period in which both tools will be available and new rules will be written in windup, and I think it's easier to translate them automatically rather than rewrite them by hand.

If we have a tool that translates the rules, with a few exceptions, why not use it with the latest windup-rulesets build?

**Comment by fabianvf** [comment]
I think our initial plan to lock in an early release seems a bit optimistic in hindsight, considering the unexpected number of contributions we've been asked to pull in. Avoiding an endless cycle of content transfer and encouraging people to learn the new format is crucial, but we also don't want to slow down adoption by missing out on key rules in our repo.

I think there are basically two ways forward, given the assumption that we do want to support at least some new content from windup
  1. **Tracking Windup Versions:** Keeping up with the latest from Windup is a simple process and keeps us updated. This will mean our 80% goal will either be pinned to a moving target, or we drop the guarantee (it's especially affected by new groovy rulesets being added, which we can't support at this moment)
  2. **Automating Rule Integration:** Developing a system for specifying Git coordinates and automating the integration process. It saves time (especially for those like Juanma doing manual conversions) and lets us pick and choose what we integrate with precision. We can include the rulesets that are asked for, and avoid pulling in groovy ones. This would be my preference I think
      - **Testing Strategy:** The only downside to this approach would be that we lose the windup testing for the targeted rulesets we're bringing in. I think this could be a great motivation to finally create our own testing format/process and convert Windup tests into ours. When we run the conversions for targeted rulesets, we could bring the tests in with them, and have them run as part of the rulesets CI. I think this would be a win/win, we'd get a testing framework for our system, pull in everything we need from windup, and avoid artificially decreasing our pass rate by pulling in new rulesets that we know we can't support

**Comment by aufi** [comment]
A lot of CI enhancement work  has been done in last months including things mentioned on this issue, closing as solved.
